// Generated by gencpp from file roborts_msgs/GimbalMode.msg
// DO NOT EDIT!


#ifndef ROBORTS_MSGS_MESSAGE_GIMBALMODE_H
#define ROBORTS_MSGS_MESSAGE_GIMBALMODE_H

#include <ros/service_traits.h>


#include <roborts_msgs/GimbalModeRequest.h>
#include <roborts_msgs/GimbalModeResponse.h>


namespace roborts_msgs
{

struct GimbalMode
{

typedef GimbalModeRequest Request;
typedef GimbalModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GimbalMode
} // namespace roborts_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roborts_msgs::GimbalMode > {
  static const char* value()
  {
    return "fcba9db77a7e7488758d65b81c19e513";
  }

  static const char* value(const ::roborts_msgs::GimbalMode&) { return value(); }
};

template<>
struct DataType< ::roborts_msgs::GimbalMode > {
  static const char* value()
  {
    return "roborts_msgs/GimbalMode";
  }

  static const char* value(const ::roborts_msgs::GimbalMode&) { return value(); }
};


// service_traits::MD5Sum< ::roborts_msgs::GimbalModeRequest> should match
// service_traits::MD5Sum< ::roborts_msgs::GimbalMode >
template<>
struct MD5Sum< ::roborts_msgs::GimbalModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roborts_msgs::GimbalMode >::value();
  }
  static const char* value(const ::roborts_msgs::GimbalModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roborts_msgs::GimbalModeRequest> should match
// service_traits::DataType< ::roborts_msgs::GimbalMode >
template<>
struct DataType< ::roborts_msgs::GimbalModeRequest>
{
  static const char* value()
  {
    return DataType< ::roborts_msgs::GimbalMode >::value();
  }
  static const char* value(const ::roborts_msgs::GimbalModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roborts_msgs::GimbalModeResponse> should match
// service_traits::MD5Sum< ::roborts_msgs::GimbalMode >
template<>
struct MD5Sum< ::roborts_msgs::GimbalModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roborts_msgs::GimbalMode >::value();
  }
  static const char* value(const ::roborts_msgs::GimbalModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roborts_msgs::GimbalModeResponse> should match
// service_traits::DataType< ::roborts_msgs::GimbalMode >
template<>
struct DataType< ::roborts_msgs::GimbalModeResponse>
{
  static const char* value()
  {
    return DataType< ::roborts_msgs::GimbalMode >::value();
  }
  static const char* value(const ::roborts_msgs::GimbalModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBORTS_MSGS_MESSAGE_GIMBALMODE_H
