// Generated by gencpp from file roborts_msgs/ShootCmd.msg
// DO NOT EDIT!


#ifndef ROBORTS_MSGS_MESSAGE_SHOOTCMD_H
#define ROBORTS_MSGS_MESSAGE_SHOOTCMD_H

#include <ros/service_traits.h>


#include <roborts_msgs/ShootCmdRequest.h>
#include <roborts_msgs/ShootCmdResponse.h>


namespace roborts_msgs
{

struct ShootCmd
{

typedef ShootCmdRequest Request;
typedef ShootCmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ShootCmd
} // namespace roborts_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roborts_msgs::ShootCmd > {
  static const char* value()
  {
    return "4a5bfc809f6670479f63201258fb4866";
  }

  static const char* value(const ::roborts_msgs::ShootCmd&) { return value(); }
};

template<>
struct DataType< ::roborts_msgs::ShootCmd > {
  static const char* value()
  {
    return "roborts_msgs/ShootCmd";
  }

  static const char* value(const ::roborts_msgs::ShootCmd&) { return value(); }
};


// service_traits::MD5Sum< ::roborts_msgs::ShootCmdRequest> should match
// service_traits::MD5Sum< ::roborts_msgs::ShootCmd >
template<>
struct MD5Sum< ::roborts_msgs::ShootCmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roborts_msgs::ShootCmd >::value();
  }
  static const char* value(const ::roborts_msgs::ShootCmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roborts_msgs::ShootCmdRequest> should match
// service_traits::DataType< ::roborts_msgs::ShootCmd >
template<>
struct DataType< ::roborts_msgs::ShootCmdRequest>
{
  static const char* value()
  {
    return DataType< ::roborts_msgs::ShootCmd >::value();
  }
  static const char* value(const ::roborts_msgs::ShootCmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roborts_msgs::ShootCmdResponse> should match
// service_traits::MD5Sum< ::roborts_msgs::ShootCmd >
template<>
struct MD5Sum< ::roborts_msgs::ShootCmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roborts_msgs::ShootCmd >::value();
  }
  static const char* value(const ::roborts_msgs::ShootCmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roborts_msgs::ShootCmdResponse> should match
// service_traits::DataType< ::roborts_msgs::ShootCmd >
template<>
struct DataType< ::roborts_msgs::ShootCmdResponse>
{
  static const char* value()
  {
    return DataType< ::roborts_msgs::ShootCmd >::value();
  }
  static const char* value(const ::roborts_msgs::ShootCmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBORTS_MSGS_MESSAGE_SHOOTCMD_H
