// Generated by gencpp from file roborts_msgs/FricWhl.msg
// DO NOT EDIT!


#ifndef ROBORTS_MSGS_MESSAGE_FRICWHL_H
#define ROBORTS_MSGS_MESSAGE_FRICWHL_H

#include <ros/service_traits.h>


#include <roborts_msgs/FricWhlRequest.h>
#include <roborts_msgs/FricWhlResponse.h>


namespace roborts_msgs
{

struct FricWhl
{

typedef FricWhlRequest Request;
typedef FricWhlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FricWhl
} // namespace roborts_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roborts_msgs::FricWhl > {
  static const char* value()
  {
    return "1a044c2743c5efe1a86f5bca57f520c6";
  }

  static const char* value(const ::roborts_msgs::FricWhl&) { return value(); }
};

template<>
struct DataType< ::roborts_msgs::FricWhl > {
  static const char* value()
  {
    return "roborts_msgs/FricWhl";
  }

  static const char* value(const ::roborts_msgs::FricWhl&) { return value(); }
};


// service_traits::MD5Sum< ::roborts_msgs::FricWhlRequest> should match
// service_traits::MD5Sum< ::roborts_msgs::FricWhl >
template<>
struct MD5Sum< ::roborts_msgs::FricWhlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roborts_msgs::FricWhl >::value();
  }
  static const char* value(const ::roborts_msgs::FricWhlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roborts_msgs::FricWhlRequest> should match
// service_traits::DataType< ::roborts_msgs::FricWhl >
template<>
struct DataType< ::roborts_msgs::FricWhlRequest>
{
  static const char* value()
  {
    return DataType< ::roborts_msgs::FricWhl >::value();
  }
  static const char* value(const ::roborts_msgs::FricWhlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roborts_msgs::FricWhlResponse> should match
// service_traits::MD5Sum< ::roborts_msgs::FricWhl >
template<>
struct MD5Sum< ::roborts_msgs::FricWhlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roborts_msgs::FricWhl >::value();
  }
  static const char* value(const ::roborts_msgs::FricWhlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roborts_msgs::FricWhlResponse> should match
// service_traits::DataType< ::roborts_msgs::FricWhl >
template<>
struct DataType< ::roborts_msgs::FricWhlResponse>
{
  static const char* value()
  {
    return DataType< ::roborts_msgs::FricWhl >::value();
  }
  static const char* value(const ::roborts_msgs::FricWhlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBORTS_MSGS_MESSAGE_FRICWHL_H
