// Generated by gencpp from file roborts_msgs/GameResult.msg
// DO NOT EDIT!


#ifndef ROBORTS_MSGS_MESSAGE_GAMERESULT_H
#define ROBORTS_MSGS_MESSAGE_GAMERESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roborts_msgs
{
template <class ContainerAllocator>
struct GameResult_
{
  typedef GameResult_<ContainerAllocator> Type;

  GameResult_()
    : result(0)  {
    }
  GameResult_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(DRAW)
  #undef DRAW
#endif
#if defined(_WIN32) && defined(RED_WIN)
  #undef RED_WIN
#endif
#if defined(_WIN32) && defined(BLUE_WIN)
  #undef BLUE_WIN
#endif

  enum {
    DRAW = 0u,
    RED_WIN = 1u,
    BLUE_WIN = 2u,
  };


  typedef boost::shared_ptr< ::roborts_msgs::GameResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roborts_msgs::GameResult_<ContainerAllocator> const> ConstPtr;

}; // struct GameResult_

typedef ::roborts_msgs::GameResult_<std::allocator<void> > GameResult;

typedef boost::shared_ptr< ::roborts_msgs::GameResult > GameResultPtr;
typedef boost::shared_ptr< ::roborts_msgs::GameResult const> GameResultConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roborts_msgs::GameResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roborts_msgs::GameResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roborts_msgs::GameResult_<ContainerAllocator1> & lhs, const ::roborts_msgs::GameResult_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roborts_msgs::GameResult_<ContainerAllocator1> & lhs, const ::roborts_msgs::GameResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roborts_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::GameResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::GameResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::GameResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::GameResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::GameResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::GameResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roborts_msgs::GameResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4d09240fdf4519a3920c8056c8354c3d";
  }

  static const char* value(const ::roborts_msgs::GameResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4d09240fdf4519a3ULL;
  static const uint64_t static_value2 = 0x920c8056c8354c3dULL;
};

template<class ContainerAllocator>
struct DataType< ::roborts_msgs::GameResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roborts_msgs/GameResult";
  }

  static const char* value(const ::roborts_msgs::GameResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roborts_msgs::GameResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#game result\n"
"uint8  DRAW=0\n"
"uint8  RED_WIN=1\n"
"uint8  BLUE_WIN=2\n"
"uint8  result\n"
;
  }

  static const char* value(const ::roborts_msgs::GameResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roborts_msgs::GameResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GameResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roborts_msgs::GameResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roborts_msgs::GameResult_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBORTS_MSGS_MESSAGE_GAMERESULT_H
