// Generated by gencpp from file roborts_msgs/GimbalModeRequest.msg
// DO NOT EDIT!


#ifndef ROBORTS_MSGS_MESSAGE_GIMBALMODEREQUEST_H
#define ROBORTS_MSGS_MESSAGE_GIMBALMODEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roborts_msgs
{
template <class ContainerAllocator>
struct GimbalModeRequest_
{
  typedef GimbalModeRequest_<ContainerAllocator> Type;

  GimbalModeRequest_()
    : gimbal_mode(0)  {
    }
  GimbalModeRequest_(const ContainerAllocator& _alloc)
    : gimbal_mode(0)  {
  (void)_alloc;
    }



   typedef uint8_t _gimbal_mode_type;
  _gimbal_mode_type gimbal_mode;





  typedef boost::shared_ptr< ::roborts_msgs::GimbalModeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roborts_msgs::GimbalModeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GimbalModeRequest_

typedef ::roborts_msgs::GimbalModeRequest_<std::allocator<void> > GimbalModeRequest;

typedef boost::shared_ptr< ::roborts_msgs::GimbalModeRequest > GimbalModeRequestPtr;
typedef boost::shared_ptr< ::roborts_msgs::GimbalModeRequest const> GimbalModeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roborts_msgs::GimbalModeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roborts_msgs::GimbalModeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roborts_msgs::GimbalModeRequest_<ContainerAllocator1> & lhs, const ::roborts_msgs::GimbalModeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.gimbal_mode == rhs.gimbal_mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roborts_msgs::GimbalModeRequest_<ContainerAllocator1> & lhs, const ::roborts_msgs::GimbalModeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roborts_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::GimbalModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::GimbalModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::GimbalModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::GimbalModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::GimbalModeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::GimbalModeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roborts_msgs::GimbalModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c87f8568799ca64a2eed82fa85fa02bb";
  }

  static const char* value(const ::roborts_msgs::GimbalModeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc87f8568799ca64aULL;
  static const uint64_t static_value2 = 0x2eed82fa85fa02bbULL;
};

template<class ContainerAllocator>
struct DataType< ::roborts_msgs::GimbalModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roborts_msgs/GimbalModeRequest";
  }

  static const char* value(const ::roborts_msgs::GimbalModeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roborts_msgs::GimbalModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 gimbal_mode\n"
;
  }

  static const char* value(const ::roborts_msgs::GimbalModeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roborts_msgs::GimbalModeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.gimbal_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GimbalModeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roborts_msgs::GimbalModeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roborts_msgs::GimbalModeRequest_<ContainerAllocator>& v)
  {
    s << indent << "gimbal_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gimbal_mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBORTS_MSGS_MESSAGE_GIMBALMODEREQUEST_H
