// Generated by gencpp from file roborts_msgs/GlobalPlannerFeedback.msg
// DO NOT EDIT!


#ifndef ROBORTS_MSGS_MESSAGE_GLOBALPLANNERFEEDBACK_H
#define ROBORTS_MSGS_MESSAGE_GLOBALPLANNERFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <nav_msgs/Path.h>

namespace roborts_msgs
{
template <class ContainerAllocator>
struct GlobalPlannerFeedback_
{
  typedef GlobalPlannerFeedback_<ContainerAllocator> Type;

  GlobalPlannerFeedback_()
    : path()
    , error_code(0)
    , error_msg()  {
    }
  GlobalPlannerFeedback_(const ContainerAllocator& _alloc)
    : path(_alloc)
    , error_code(0)
    , error_msg(_alloc)  {
  (void)_alloc;
    }



   typedef  ::nav_msgs::Path_<ContainerAllocator>  _path_type;
  _path_type path;

   typedef int32_t _error_code_type;
  _error_code_type error_code;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _error_msg_type;
  _error_msg_type error_msg;





  typedef boost::shared_ptr< ::roborts_msgs::GlobalPlannerFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roborts_msgs::GlobalPlannerFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct GlobalPlannerFeedback_

typedef ::roborts_msgs::GlobalPlannerFeedback_<std::allocator<void> > GlobalPlannerFeedback;

typedef boost::shared_ptr< ::roborts_msgs::GlobalPlannerFeedback > GlobalPlannerFeedbackPtr;
typedef boost::shared_ptr< ::roborts_msgs::GlobalPlannerFeedback const> GlobalPlannerFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roborts_msgs::GlobalPlannerFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roborts_msgs::GlobalPlannerFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roborts_msgs::GlobalPlannerFeedback_<ContainerAllocator1> & lhs, const ::roborts_msgs::GlobalPlannerFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.path == rhs.path &&
    lhs.error_code == rhs.error_code &&
    lhs.error_msg == rhs.error_msg;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roborts_msgs::GlobalPlannerFeedback_<ContainerAllocator1> & lhs, const ::roborts_msgs::GlobalPlannerFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roborts_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::GlobalPlannerFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::GlobalPlannerFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::GlobalPlannerFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::GlobalPlannerFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::GlobalPlannerFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::GlobalPlannerFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roborts_msgs::GlobalPlannerFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f3dbb0203aeb8ca03ec5019146bf73fa";
  }

  static const char* value(const ::roborts_msgs::GlobalPlannerFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf3dbb0203aeb8ca0ULL;
  static const uint64_t static_value2 = 0x3ec5019146bf73faULL;
};

template<class ContainerAllocator>
struct DataType< ::roborts_msgs::GlobalPlannerFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roborts_msgs/GlobalPlannerFeedback";
  }

  static const char* value(const ::roborts_msgs::GlobalPlannerFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roborts_msgs::GlobalPlannerFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"nav_msgs/Path path\n"
"int32  error_code\n"
"string error_msg\n"
"\n"
"================================================================================\n"
"MSG: nav_msgs/Path\n"
"#An array of poses that represents a Path for a robot to follow\n"
"Header header\n"
"geometry_msgs/PoseStamped[] poses\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::roborts_msgs::GlobalPlannerFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roborts_msgs::GlobalPlannerFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.path);
      stream.next(m.error_code);
      stream.next(m.error_msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GlobalPlannerFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roborts_msgs::GlobalPlannerFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roborts_msgs::GlobalPlannerFeedback_<ContainerAllocator>& v)
  {
    s << indent << "path: ";
    s << std::endl;
    Printer< ::nav_msgs::Path_<ContainerAllocator> >::stream(s, indent + "  ", v.path);
    s << indent << "error_code: ";
    Printer<int32_t>::stream(s, indent + "  ", v.error_code);
    s << indent << "error_msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.error_msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBORTS_MSGS_MESSAGE_GLOBALPLANNERFEEDBACK_H
