// Generated by gencpp from file roborts_msgs/LocalPlannerFeedback.msg
// DO NOT EDIT!


#ifndef ROBORTS_MSGS_MESSAGE_LOCALPLANNERFEEDBACK_H
#define ROBORTS_MSGS_MESSAGE_LOCALPLANNERFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roborts_msgs
{
template <class ContainerAllocator>
struct LocalPlannerFeedback_
{
  typedef LocalPlannerFeedback_<ContainerAllocator> Type;

  LocalPlannerFeedback_()
    : error_code(0)
    , error_msg()  {
    }
  LocalPlannerFeedback_(const ContainerAllocator& _alloc)
    : error_code(0)
    , error_msg(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _error_code_type;
  _error_code_type error_code;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _error_msg_type;
  _error_msg_type error_msg;





  typedef boost::shared_ptr< ::roborts_msgs::LocalPlannerFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roborts_msgs::LocalPlannerFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct LocalPlannerFeedback_

typedef ::roborts_msgs::LocalPlannerFeedback_<std::allocator<void> > LocalPlannerFeedback;

typedef boost::shared_ptr< ::roborts_msgs::LocalPlannerFeedback > LocalPlannerFeedbackPtr;
typedef boost::shared_ptr< ::roborts_msgs::LocalPlannerFeedback const> LocalPlannerFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roborts_msgs::LocalPlannerFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roborts_msgs::LocalPlannerFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roborts_msgs::LocalPlannerFeedback_<ContainerAllocator1> & lhs, const ::roborts_msgs::LocalPlannerFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.error_code == rhs.error_code &&
    lhs.error_msg == rhs.error_msg;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roborts_msgs::LocalPlannerFeedback_<ContainerAllocator1> & lhs, const ::roborts_msgs::LocalPlannerFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roborts_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::LocalPlannerFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::LocalPlannerFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::LocalPlannerFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::LocalPlannerFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::LocalPlannerFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::LocalPlannerFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roborts_msgs::LocalPlannerFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a8db3a24aeaa9eb2bfabe9e5577dcde1";
  }

  static const char* value(const ::roborts_msgs::LocalPlannerFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa8db3a24aeaa9eb2ULL;
  static const uint64_t static_value2 = 0xbfabe9e5577dcde1ULL;
};

template<class ContainerAllocator>
struct DataType< ::roborts_msgs::LocalPlannerFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roborts_msgs/LocalPlannerFeedback";
  }

  static const char* value(const ::roborts_msgs::LocalPlannerFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roborts_msgs::LocalPlannerFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"int32  error_code\n"
"string error_msg\n"
;
  }

  static const char* value(const ::roborts_msgs::LocalPlannerFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roborts_msgs::LocalPlannerFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.error_code);
      stream.next(m.error_msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LocalPlannerFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roborts_msgs::LocalPlannerFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roborts_msgs::LocalPlannerFeedback_<ContainerAllocator>& v)
  {
    s << indent << "error_code: ";
    Printer<int32_t>::stream(s, indent + "  ", v.error_code);
    s << indent << "error_msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.error_msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBORTS_MSGS_MESSAGE_LOCALPLANNERFEEDBACK_H
