// Generated by gencpp from file roborts_msgs/ProjectileSupply.msg
// DO NOT EDIT!


#ifndef ROBORTS_MSGS_MESSAGE_PROJECTILESUPPLY_H
#define ROBORTS_MSGS_MESSAGE_PROJECTILESUPPLY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roborts_msgs
{
template <class ContainerAllocator>
struct ProjectileSupply_
{
  typedef ProjectileSupply_<ContainerAllocator> Type;

  ProjectileSupply_()
    : number(0)  {
    }
  ProjectileSupply_(const ContainerAllocator& _alloc)
    : number(0)  {
  (void)_alloc;
    }



   typedef uint8_t _number_type;
  _number_type number;





  typedef boost::shared_ptr< ::roborts_msgs::ProjectileSupply_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roborts_msgs::ProjectileSupply_<ContainerAllocator> const> ConstPtr;

}; // struct ProjectileSupply_

typedef ::roborts_msgs::ProjectileSupply_<std::allocator<void> > ProjectileSupply;

typedef boost::shared_ptr< ::roborts_msgs::ProjectileSupply > ProjectileSupplyPtr;
typedef boost::shared_ptr< ::roborts_msgs::ProjectileSupply const> ProjectileSupplyConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roborts_msgs::ProjectileSupply_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roborts_msgs::ProjectileSupply_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roborts_msgs::ProjectileSupply_<ContainerAllocator1> & lhs, const ::roborts_msgs::ProjectileSupply_<ContainerAllocator2> & rhs)
{
  return lhs.number == rhs.number;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roborts_msgs::ProjectileSupply_<ContainerAllocator1> & lhs, const ::roborts_msgs::ProjectileSupply_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roborts_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::ProjectileSupply_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::ProjectileSupply_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::ProjectileSupply_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::ProjectileSupply_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::ProjectileSupply_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::ProjectileSupply_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roborts_msgs::ProjectileSupply_<ContainerAllocator> >
{
  static const char* value()
  {
    return "29e94f7568510a2f9241abcc8f191b4f";
  }

  static const char* value(const ::roborts_msgs::ProjectileSupply_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x29e94f7568510a2fULL;
  static const uint64_t static_value2 = 0x9241abcc8f191b4fULL;
};

template<class ContainerAllocator>
struct DataType< ::roborts_msgs::ProjectileSupply_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roborts_msgs/ProjectileSupply";
  }

  static const char* value(const ::roborts_msgs::ProjectileSupply_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roborts_msgs::ProjectileSupply_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#projectile supply\n"
"uint8 number\n"
;
  }

  static const char* value(const ::roborts_msgs::ProjectileSupply_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roborts_msgs::ProjectileSupply_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ProjectileSupply_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roborts_msgs::ProjectileSupply_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roborts_msgs::ProjectileSupply_<ContainerAllocator>& v)
  {
    s << indent << "number: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBORTS_MSGS_MESSAGE_PROJECTILESUPPLY_H
