// Generated by gencpp from file roborts_msgs/RobotHeat.msg
// DO NOT EDIT!


#ifndef ROBORTS_MSGS_MESSAGE_ROBOTHEAT_H
#define ROBORTS_MSGS_MESSAGE_ROBOTHEAT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roborts_msgs
{
template <class ContainerAllocator>
struct RobotHeat_
{
  typedef RobotHeat_<ContainerAllocator> Type;

  RobotHeat_()
    : chassis_volt(0)
    , chassis_current(0)
    , chassis_power(0.0)
    , chassis_power_buffer(0)
    , shooter_heat(0)  {
    }
  RobotHeat_(const ContainerAllocator& _alloc)
    : chassis_volt(0)
    , chassis_current(0)
    , chassis_power(0.0)
    , chassis_power_buffer(0)
    , shooter_heat(0)  {
  (void)_alloc;
    }



   typedef uint16_t _chassis_volt_type;
  _chassis_volt_type chassis_volt;

   typedef uint16_t _chassis_current_type;
  _chassis_current_type chassis_current;

   typedef double _chassis_power_type;
  _chassis_power_type chassis_power;

   typedef uint16_t _chassis_power_buffer_type;
  _chassis_power_buffer_type chassis_power_buffer;

   typedef uint16_t _shooter_heat_type;
  _shooter_heat_type shooter_heat;





  typedef boost::shared_ptr< ::roborts_msgs::RobotHeat_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roborts_msgs::RobotHeat_<ContainerAllocator> const> ConstPtr;

}; // struct RobotHeat_

typedef ::roborts_msgs::RobotHeat_<std::allocator<void> > RobotHeat;

typedef boost::shared_ptr< ::roborts_msgs::RobotHeat > RobotHeatPtr;
typedef boost::shared_ptr< ::roborts_msgs::RobotHeat const> RobotHeatConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roborts_msgs::RobotHeat_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roborts_msgs::RobotHeat_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roborts_msgs::RobotHeat_<ContainerAllocator1> & lhs, const ::roborts_msgs::RobotHeat_<ContainerAllocator2> & rhs)
{
  return lhs.chassis_volt == rhs.chassis_volt &&
    lhs.chassis_current == rhs.chassis_current &&
    lhs.chassis_power == rhs.chassis_power &&
    lhs.chassis_power_buffer == rhs.chassis_power_buffer &&
    lhs.shooter_heat == rhs.shooter_heat;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roborts_msgs::RobotHeat_<ContainerAllocator1> & lhs, const ::roborts_msgs::RobotHeat_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roborts_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::RobotHeat_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::RobotHeat_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::RobotHeat_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::RobotHeat_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::RobotHeat_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::RobotHeat_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roborts_msgs::RobotHeat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "12a69f2d33ac7367772428034e998f18";
  }

  static const char* value(const ::roborts_msgs::RobotHeat_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x12a69f2d33ac7367ULL;
  static const uint64_t static_value2 = 0x772428034e998f18ULL;
};

template<class ContainerAllocator>
struct DataType< ::roborts_msgs::RobotHeat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roborts_msgs/RobotHeat";
  }

  static const char* value(const ::roborts_msgs::RobotHeat_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roborts_msgs::RobotHeat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#robot power and heat data\n"
"uint16 chassis_volt\n"
"uint16 chassis_current\n"
"float64  chassis_power\n"
"uint16 chassis_power_buffer\n"
"uint16 shooter_heat\n"
"\n"
;
  }

  static const char* value(const ::roborts_msgs::RobotHeat_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roborts_msgs::RobotHeat_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.chassis_volt);
      stream.next(m.chassis_current);
      stream.next(m.chassis_power);
      stream.next(m.chassis_power_buffer);
      stream.next(m.shooter_heat);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotHeat_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roborts_msgs::RobotHeat_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roborts_msgs::RobotHeat_<ContainerAllocator>& v)
  {
    s << indent << "chassis_volt: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.chassis_volt);
    s << indent << "chassis_current: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.chassis_current);
    s << indent << "chassis_power: ";
    Printer<double>::stream(s, indent + "  ", v.chassis_power);
    s << indent << "chassis_power_buffer: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.chassis_power_buffer);
    s << indent << "shooter_heat: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.shooter_heat);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBORTS_MSGS_MESSAGE_ROBOTHEAT_H
