// Generated by gencpp from file roborts_msgs/RobotShoot.msg
// DO NOT EDIT!


#ifndef ROBORTS_MSGS_MESSAGE_ROBOTSHOOT_H
#define ROBORTS_MSGS_MESSAGE_ROBOTSHOOT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roborts_msgs
{
template <class ContainerAllocator>
struct RobotShoot_
{
  typedef RobotShoot_<ContainerAllocator> Type;

  RobotShoot_()
    : frequency(0)
    , speed(0.0)  {
    }
  RobotShoot_(const ContainerAllocator& _alloc)
    : frequency(0)
    , speed(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _frequency_type;
  _frequency_type frequency;

   typedef double _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::roborts_msgs::RobotShoot_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roborts_msgs::RobotShoot_<ContainerAllocator> const> ConstPtr;

}; // struct RobotShoot_

typedef ::roborts_msgs::RobotShoot_<std::allocator<void> > RobotShoot;

typedef boost::shared_ptr< ::roborts_msgs::RobotShoot > RobotShootPtr;
typedef boost::shared_ptr< ::roborts_msgs::RobotShoot const> RobotShootConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roborts_msgs::RobotShoot_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roborts_msgs::RobotShoot_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roborts_msgs::RobotShoot_<ContainerAllocator1> & lhs, const ::roborts_msgs::RobotShoot_<ContainerAllocator2> & rhs)
{
  return lhs.frequency == rhs.frequency &&
    lhs.speed == rhs.speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roborts_msgs::RobotShoot_<ContainerAllocator1> & lhs, const ::roborts_msgs::RobotShoot_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roborts_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::RobotShoot_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::RobotShoot_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::RobotShoot_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::RobotShoot_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::RobotShoot_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::RobotShoot_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roborts_msgs::RobotShoot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2634dbd94553eb6552f07bddaa5136d1";
  }

  static const char* value(const ::roborts_msgs::RobotShoot_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2634dbd94553eb65ULL;
  static const uint64_t static_value2 = 0x52f07bddaa5136d1ULL;
};

template<class ContainerAllocator>
struct DataType< ::roborts_msgs::RobotShoot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roborts_msgs/RobotShoot";
  }

  static const char* value(const ::roborts_msgs::RobotShoot_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roborts_msgs::RobotShoot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#robot shoot data\n"
"uint8 frequency\n"
"float64 speed\n"
;
  }

  static const char* value(const ::roborts_msgs::RobotShoot_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roborts_msgs::RobotShoot_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frequency);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotShoot_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roborts_msgs::RobotShoot_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roborts_msgs::RobotShoot_<ContainerAllocator>& v)
  {
    s << indent << "frequency: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.frequency);
    s << indent << "speed: ";
    Printer<double>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBORTS_MSGS_MESSAGE_ROBOTSHOOT_H
