// Generated by gencpp from file roborts_msgs/ShootCmdRequest.msg
// DO NOT EDIT!


#ifndef ROBORTS_MSGS_MESSAGE_SHOOTCMDREQUEST_H
#define ROBORTS_MSGS_MESSAGE_SHOOTCMDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roborts_msgs
{
template <class ContainerAllocator>
struct ShootCmdRequest_
{
  typedef ShootCmdRequest_<ContainerAllocator> Type;

  ShootCmdRequest_()
    : mode(0)
    , number(0)  {
    }
  ShootCmdRequest_(const ContainerAllocator& _alloc)
    : mode(0)
    , number(0)  {
  (void)_alloc;
    }



   typedef uint8_t _mode_type;
  _mode_type mode;

   typedef uint8_t _number_type;
  _number_type number;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(STOP)
  #undef STOP
#endif
#if defined(_WIN32) && defined(ONCE)
  #undef ONCE
#endif
#if defined(_WIN32) && defined(CONTINUOUS)
  #undef CONTINUOUS
#endif

  enum {
    STOP = 0u,
    ONCE = 1u,
    CONTINUOUS = 2u,
  };


  typedef boost::shared_ptr< ::roborts_msgs::ShootCmdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roborts_msgs::ShootCmdRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ShootCmdRequest_

typedef ::roborts_msgs::ShootCmdRequest_<std::allocator<void> > ShootCmdRequest;

typedef boost::shared_ptr< ::roborts_msgs::ShootCmdRequest > ShootCmdRequestPtr;
typedef boost::shared_ptr< ::roborts_msgs::ShootCmdRequest const> ShootCmdRequestConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roborts_msgs::ShootCmdRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roborts_msgs::ShootCmdRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roborts_msgs::ShootCmdRequest_<ContainerAllocator1> & lhs, const ::roborts_msgs::ShootCmdRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode &&
    lhs.number == rhs.number;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roborts_msgs::ShootCmdRequest_<ContainerAllocator1> & lhs, const ::roborts_msgs::ShootCmdRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roborts_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::ShootCmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::ShootCmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::ShootCmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::ShootCmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::ShootCmdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::ShootCmdRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roborts_msgs::ShootCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e60d1d1007f97ae14e2d2f584fbf2502";
  }

  static const char* value(const ::roborts_msgs::ShootCmdRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe60d1d1007f97ae1ULL;
  static const uint64_t static_value2 = 0x4e2d2f584fbf2502ULL;
};

template<class ContainerAllocator>
struct DataType< ::roborts_msgs::ShootCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roborts_msgs/ShootCmdRequest";
  }

  static const char* value(const ::roborts_msgs::ShootCmdRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roborts_msgs::ShootCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 STOP = 0\n"
"uint8 ONCE = 1\n"
"uint8 CONTINUOUS = 2\n"
"uint8 mode\n"
"uint8 number\n"
;
  }

  static const char* value(const ::roborts_msgs::ShootCmdRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roborts_msgs::ShootCmdRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
      stream.next(m.number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ShootCmdRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roborts_msgs::ShootCmdRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roborts_msgs::ShootCmdRequest_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "number: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBORTS_MSGS_MESSAGE_SHOOTCMDREQUEST_H
