// Generated by gencpp from file roborts_msgs/SupplierStatus.msg
// DO NOT EDIT!


#ifndef ROBORTS_MSGS_MESSAGE_SUPPLIERSTATUS_H
#define ROBORTS_MSGS_MESSAGE_SUPPLIERSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roborts_msgs
{
template <class ContainerAllocator>
struct SupplierStatus_
{
  typedef SupplierStatus_<ContainerAllocator> Type;

  SupplierStatus_()
    : status(0)  {
    }
  SupplierStatus_(const ContainerAllocator& _alloc)
    : status(0)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(CLOSE)
  #undef CLOSE
#endif
#if defined(_WIN32) && defined(PREPARING)
  #undef PREPARING
#endif
#if defined(_WIN32) && defined(SUPPLYING)
  #undef SUPPLYING
#endif

  enum {
    CLOSE = 0u,
    PREPARING = 1u,
    SUPPLYING = 2u,
  };


  typedef boost::shared_ptr< ::roborts_msgs::SupplierStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roborts_msgs::SupplierStatus_<ContainerAllocator> const> ConstPtr;

}; // struct SupplierStatus_

typedef ::roborts_msgs::SupplierStatus_<std::allocator<void> > SupplierStatus;

typedef boost::shared_ptr< ::roborts_msgs::SupplierStatus > SupplierStatusPtr;
typedef boost::shared_ptr< ::roborts_msgs::SupplierStatus const> SupplierStatusConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roborts_msgs::SupplierStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roborts_msgs::SupplierStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roborts_msgs::SupplierStatus_<ContainerAllocator1> & lhs, const ::roborts_msgs::SupplierStatus_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roborts_msgs::SupplierStatus_<ContainerAllocator1> & lhs, const ::roborts_msgs::SupplierStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roborts_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::SupplierStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::SupplierStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::SupplierStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::SupplierStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::SupplierStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::SupplierStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roborts_msgs::SupplierStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "81f3d032e85b689acf259876e6f8d051";
  }

  static const char* value(const ::roborts_msgs::SupplierStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x81f3d032e85b689aULL;
  static const uint64_t static_value2 = 0xcf259876e6f8d051ULL;
};

template<class ContainerAllocator>
struct DataType< ::roborts_msgs::SupplierStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roborts_msgs/SupplierStatus";
  }

  static const char* value(const ::roborts_msgs::SupplierStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roborts_msgs::SupplierStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#supplier status\n"
"uint8 CLOSE = 0\n"
"uint8 PREPARING = 1\n"
"uint8 SUPPLYING = 2\n"
"uint8 status\n"
"\n"
;
  }

  static const char* value(const ::roborts_msgs::SupplierStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roborts_msgs::SupplierStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SupplierStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roborts_msgs::SupplierStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roborts_msgs::SupplierStatus_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBORTS_MSGS_MESSAGE_SUPPLIERSTATUS_H
